29-cart page
hermomy/orvar pull request #35
Opened 2019-04-16 07:28 UTC by akashaf

2019-04-18 02:18 UTC, tienping requested changes

2019-04-18 02:18 UTC, tienping commented on app/containers/CheckoutPage/saga.js
> +        // yield put(listingRequestFailed(response.data));
i think we will need this failed handling

2019-04-18 02:18 UTC, tienping commented on app/containers/CheckoutPage/reducer.js
> +                .set('data', dataChecking(action, 'r', 'cart'));
can u give proper name for r?
e.g. response

2019-04-18 02:18 UTC, tienping commented on app/containers/CheckoutPage/reducer.js
> +                .set('data', dataChecking(action, 'r', 'cart'));
or, payload

2019-04-23 03:52 UTC, tienping requested changes

2019-04-23 03:52 UTC, tienping commented on app/components/CartPage/index.js
> +    is_qty_adjustable = (item) => {
function use camel case

2019-04-23 03:52 UTC, tienping commented on app/components/CartPage/index.js
> +    is_qty_adjustable = (item) => {
isQtyAdjustable suppose to return boolean, if this is suppose to return element, use renderQuantityEditor instead

2019-04-23 03:52 UTC, tienping commented on app/components/CartPage/index.js
> +                        onClick={() => this.props.addQty('remove', item.qty, item.id)}
use this.addQty?

2019-04-23 03:52 UTC, tienping commented on app/components/CartPage/index.js
> +                        onClick={() => this.props.addQty('remove', item.qty, item.id)}
btw... how can addQty support remove, rename the function to changeQuantity

2019-04-23 03:52 UTC, tienping commented on app/containers/CheckoutPage/index.js
> +        quantity = type === 'add' ? quantity += 1 : quantity -= 1;
quantity += type === 'add' ? 1 : -1;

2019-04-23 03:52 UTC, tienping commented on app/containers/CheckoutPage/reducer.js
> +        case GET_CHECKOUT_DATA:
u dint handle for failed at all?

2019-04-25 07:03 UTC, akashaf commented on app/components/CartPage/index.js
> +                        onClick={() => this.props.addQty('remove', item.qty, item.id)}
this function is use for update qty. will change it..

2019-05-03 06:53 UTC, tienping approved these changes

2019-05-03 06:53 UTC, merged