profile page update
hermomy/orvar pull request #37
Opened 2019-04-23 01:09 UTC by jbterrylin

2019-04-23 08:40 UTC, tienping requested changes

2019-04-23 08:40 UTC, tienping commented on app/components/Pagination/index.js
> +        if (!this.props.checking) {
change to this.props.isHerlisting, boolean

2019-04-23 08:40 UTC, tienping commented on app/components/ProductCard/index.js
> +        if (!this.props.cross) {
this.props.allowDelete, boolean

2019-04-23 08:40 UTC, tienping commented on app/components/ProductCard/index.js
> +                        {this.renderCross()}
```
{
    this.props.allowDelete &&
        <div onClick={() => this.props.deleteFromWishlist()}>
            <i className="fa fa-times cross-icon" aria-hidden="true"></i>
        </div>
}
```

2019-04-23 08:40 UTC, tienping commented on app/components/ProductCard/index.js
> +                                    className={`wishlist-btn fa fa-heart ${true ? 'wishlist-btn-clicked' : ''}`}
fix this hardcoded value

2019-04-23 08:40 UTC, tienping commented on app/containers/App/index.js
> +                        <Route exact={true} path="/profile1/" component={ProfileWholePage} />
profile1??

2019-04-23 08:40 UTC, tienping commented on app/containers/ProfileReview/index.js
> +        obj[`${id}`] = mark;
obj[id] = mark;

2019-04-29 09:03 UTC, tienping approved these changes

2019-04-29 09:06 UTC, jbterrylin commented
fix code done

2019-04-29 09:15 UTC, merged